matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      before_script:
        - chmod u+x gradlew
      script:
        - ./gradlew build -PANDORID
        - ./gradlew clean build -PJS -PNATIVE
    - os: osx
      osx_image: xcode8
      before_script:
        - chmod u+x gradlew
      script:
        - ./gradlew build -PANDROID
        - ./gradlew clean build -PJS -PNATIVE
